<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <NuGetAudit>false</NuGetAudit>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RedirectOutput.fs" />
    <Compile Include="Sample.fs" />
    <Compile Include="TestDocCoverage.fs" />
    <Compile Include="TestDocCoverageCSharp.fs" />
    <Compile Include="TestSemanticVersioning.fs" />
    <Compile Include="TestSurface.fs" />
    <Compile Include="TestSurfaceComparison.fs" />
    <Compile Include="TestApiSurface.fs" />
    <Compile Include="TestMonotonicVersion.fs" />
    <Compile Include="TestType.fs" />
    <Compile Include="TestVersionFile.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck" Version="3.4.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="FsUnit" Version="7.1.1" />
    <PackageReference Include="NUnit" Version="4.5.0" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="4.2.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ApiSurface.CSharpExample\ApiSurface.CSharpExample.csproj" />
    <ProjectReference Include="..\..\ApiSurface.DocumentationSample\ApiSurface.DocumentationSample.fsproj" />
    <ProjectReference Include="..\..\ApiSurface\ApiSurface.fsproj" />
    <ProjectReference Include="..\..\ApiSurface.SampleAssembly\ApiSurface.SampleAssembly.fsproj" />
  </ItemGroup>
</Project>
